backend:
  name: git-gateway

collections:
  - name: redirects
    label: Redirects
    folder: "content/redirects"
    create: true
    format: json
    slug: "{{slug}}"
    identifier_field: from
    fields:
      - {label: "From", name: "from", widget: "string"}
      - {label: "To", name: "to", widget: "string"}
